export const PRIMARY_COLORS = {
  pink: '--base-pink-60',
  red: '--base-red-60',
  orange: '--base-orange-70',
  yellow: '--base-yellow-85',
  green: '--base-green-70',
  sky: '--base-sky-75',
  blue: '--base-blue-50',
  violet: '--base-violet-45',
  graphite: '--base-graphite-15',
  gray: '--base-gray-15',
};

export const COLOR_VARIABLES = [
  // Pink
  '--base-pink-5',
  '--base-pink-10',
  '--base-pink-15',
  '--base-pink-20',
  '--base-pink-25',
  '--base-pink-30',
  '--base-pink-35',
  '--base-pink-40',
  '--base-pink-45',
  '--base-pink-50',
  '--base-pink-55',
  '--base-pink-60',
  '--base-pink-65',
  '--base-pink-70',
  '--base-pink-75',
  '--base-pink-80',
  '--base-pink-85',
  '--base-pink-90',
  '--base-pink-95',
  '--base-pink-96',
  '--base-pink-97',

  // Red
  '--base-red-5',
  '--base-red-10',
  '--base-red-15',
  '--base-red-20',
  '--base-red-25',
  '--base-red-30',
  '--base-red-35',
  '--base-red-40',
  '--base-red-45',
  '--base-red-50',
  '--base-red-55',
  '--base-red-60',
  '--base-red-65',
  '--base-red-70',
  '--base-red-75',
  '--base-red-80',
  '--base-red-85',
  '--base-red-90',
  '--base-red-95',
  '--base-red-96',
  '--base-red-97',

  // Orange
  '--base-orange-5',
  '--base-orange-10',
  '--base-orange-15',
  '--base-orange-20',
  '--base-orange-25',
  '--base-orange-30',
  '--base-orange-35',
  '--base-orange-40',
  '--base-orange-45',
  '--base-orange-50',
  '--base-orange-55',
  '--base-orange-60',
  '--base-orange-65',
  '--base-orange-70',
  '--base-orange-75',
  '--base-orange-80',
  '--base-orange-85',
  '--base-orange-90',
  '--base-orange-95',
  '--base-orange-96',
  '--base-orange-97',

  // Yellow
  '--base-yellow-5',
  '--base-yellow-10',
  '--base-yellow-15',
  '--base-yellow-20',
  '--base-yellow-25',
  '--base-yellow-30',
  '--base-yellow-35',
  '--base-yellow-40',
  '--base-yellow-45',
  '--base-yellow-50',
  '--base-yellow-55',
  '--base-yellow-60',
  '--base-yellow-65',
  '--base-yellow-70',
  '--base-yellow-75',
  '--base-yellow-80',
  '--base-yellow-85',
  '--base-yellow-90',
  '--base-yellow-95',
  '--base-yellow-96',
  '--base-yellow-97',

  // Green
  '--base-green-5',
  '--base-green-10',
  '--base-green-15',
  '--base-green-20',
  '--base-green-25',
  '--base-green-30',
  '--base-green-35',
  '--base-green-40',
  '--base-green-45',
  '--base-green-50',
  '--base-green-55',
  '--base-green-60',
  '--base-green-65',
  '--base-green-70',
  '--base-green-75',
  '--base-green-80',
  '--base-green-85',
  '--base-green-90',
  '--base-green-95',
  '--base-green-96',
  '--base-green-97',

  // Sky
  '--base-sky-5',
  '--base-sky-10',
  '--base-sky-15',
  '--base-sky-20',
  '--base-sky-25',
  '--base-sky-30',
  '--base-sky-35',
  '--base-sky-40',
  '--base-sky-45',
  '--base-sky-50',
  '--base-sky-55',
  '--base-sky-60',
  '--base-sky-65',
  '--base-sky-70',
  '--base-sky-75',
  '--base-sky-80',
  '--base-sky-85',
  '--base-sky-90',
  '--base-sky-95',
  '--base-sky-96',
  '--base-sky-97',

  // Blue
  '--base-blue-5',
  '--base-blue-10',
  '--base-blue-15',
  '--base-blue-20',
  '--base-blue-25',
  '--base-blue-30',
  '--base-blue-35',
  '--base-blue-40',
  '--base-blue-45',
  '--base-blue-50',
  '--base-blue-55',
  '--base-blue-60',
  '--base-blue-65',
  '--base-blue-70',
  '--base-blue-75',
  '--base-blue-80',
  '--base-blue-85',
  '--base-blue-90',
  '--base-blue-95',
  '--base-blue-96',
  '--base-blue-97',
  '--base-blue-98',

  // Violet
  '--base-violet-5',
  '--base-violet-10',
  '--base-violet-15',
  '--base-violet-20',
  '--base-violet-25',
  '--base-violet-30',
  '--base-violet-35',
  '--base-violet-40',
  '--base-violet-45',
  '--base-violet-50',
  '--base-violet-55',
  '--base-violet-60',
  '--base-violet-65',
  '--base-violet-70',
  '--base-violet-75',
  '--base-violet-80',
  '--base-violet-85',
  '--base-violet-90',
  '--base-violet-95',
  '--base-violet-96',
  '--base-violet-97',

  // Graphite
  '--base-graphite-5',
  '--base-graphite-10',
  '--base-graphite-15',
  '--base-graphite-20',
  '--base-graphite-25',
  '--base-graphite-30',
  '--base-graphite-35',
  '--base-graphite-40',
  '--base-graphite-45',
  '--base-graphite-50',
  '--base-graphite-55',
  '--base-graphite-60',
  '--base-graphite-65',
  '--base-graphite-70',
  '--base-graphite-75',
  '--base-graphite-80',
  '--base-graphite-85',
  '--base-graphite-90',
  '--base-graphite-94',
  '--base-graphite-95',
  '--base-graphite-96',
  '--base-graphite-97',
  '--base-graphite-98',

  // Gray
  '--base-gray-0',
  '--base-gray-5',
  '--base-gray-10',
  '--base-gray-15',
  '--base-gray-20',
  '--base-gray-25',
  '--base-gray-30',
  '--base-gray-35',
  '--base-gray-40',
  '--base-gray-45',
  '--base-gray-50',
  '--base-gray-55',
  '--base-gray-60',
  '--base-gray-65',
  '--base-gray-70',
  '--base-gray-75',
  '--base-gray-80',
  '--base-gray-85',
  '--base-gray-90',
  '--base-gray-95',
  '--base-gray-96',
  '--base-gray-97',
];
